---
#- name: Ensure the destination has been set
#  fail:
#    msg: The variable {{ item }} has not been defined.
#  when: item is undefined
#  loop:
#    - download_url
#    - checksum_url
#    - dest
- name: Download the checksum from {{ checksum_url }}
  uri:
    url: "{{ checksum_url }}"
    return_content: yes
  register: checksum
- name: Download the file from {{ download_url }}
  get_url:
    url: "{{ download_url }}"
    dest: "{{ dest }}"
    checksum: sha512:{{ checksum.content.split()[0] }}
