---
- name: Copy init file to /etc/init.d
  copy:
    src: "{{ galaxy.home }}/contrib/galaxy.debian-init"
    dest: /etc/init.d/galaxy
    mode: '0755'
    remote_src: yes
- name: Change home to {{ galaxy.home }}
  replace:
    path: /etc/init.d/galaxy
    regexp: galaxy_dist
    replace: galaxy
- name: Signal that the service has been configured
  set_fact:
    service_configured: yes
