---
# Steps needed to customized a default Galaxy installation for the LAPPS Grid.
- name: Link the LAPPS Python lib
  file:
    src: "{{ mods.home }}/lib/lappsgrid"
    dest: "{{ galaxy.home }}/lib/lappsgrid"
    state: link
    owner: "{{ galaxy.user }}"
    group: "{{ galaxy.user }}"
- name: Link the welcome_url
  file:
    src: "{{ mods.home }}/index.html"
    dest: "{{ galaxy.home }}/static/index.html"
    state: link
    owner: "{{ galaxy.user }}"
    group: "{{ galaxy.user }}"
#- name: Modify the masthead to read "LAPPS / Galaxy"
#  lineinfile:
#    path: "{{ galaxy.home }}/client/galaxy/scripts/layout/masthead.js"
#    regexp: '^this.$navbarBrandTitle'
#    line: this.$navbarBrandTitle.html(`${(this.options.brand && `${this.options.brand} /`) || ""} Galaxy`);

