---
- hosts: localhost
  tasks:
  - name: Check
    fail:
      msg: "{{ item }} not defined"
    when: "item is undefined"
    loop: ['v1','v2','v3']
  - name: Test vars
    debug:
      msg: Loop {{ item }}
    loop:
      - "{{ v1 }}"
      - "{{ v2 }}"
      - "{{ v3 }}"
