---
- hosts: localhost
  vars_files:
    - vars.yml
  tasks:
  - name: Test vars
    vars:
      options:
        opt2: custom value
    debug:
      var: options
#      msg: Option {{ item.n }} {{ item.value }}
#    loop:
#      - n: 1
#        value: "{{ opt1 }}"
#      - n: 2
#        value: "{{ opt2 }}"
#      - n: 3
#        value: "{{ opt3 }}"
