---
galaxy_branch: saml.experiment
mods_branch: master

galaxy:
  port: 8000
  user: galaxy
  root: /home/galaxy
  branch: "{{ galaxy_branch }}"
  home: /home/galaxy/galaxy
  repo: https://github.com/lappsgrid-incubator/Galaxy.git

mods:
  branch: "{{ mods_branch }}"
  home: /home/galaxy/mods
  repo: https://github.com/lappsgrid-incubator/GalaxyMods.git

project:
  port: 8000
  user: galaxy
  root: /home/galaxy
  branch: release_19.09
  home: /home/galaxy/galaxy
  repo: https://github.com/galaxyproject/galaxy.git

