---
- hosts: galaxy
  become: yes
  vars:
    # The location of the LAPPS Grid certificates and private key.  These must be loaded from a secure
    # location on your local machine.
    # DO NOT CHECK THE PRIVATE KEY INTO SOURCE CONTROL!
    certificate_path: /Users/suderman/certs/2018
    #ssl_path: /etc/ssl
    required_modules:
      - headers
      - rewrite
      - proxy
      - proxy_http
  tasks:
    - name: System configuration (Debian|Ubuntu)
      set_fact:
        os_debian: yes
        os_redhat: no
        package_name: apache2
        config_path: /etc/apache2/sites-available
        ssl_path: /etc/apache2/ssl
        log_dir: /var/log/apache2
      when: ansible_os_family == 'Debian'
    - name: System configuration (RedHat|CentOS)
      set_fact:
        os_debian: no
        os_redhat: yes
        package_name: httpd
        config_path: /etc/httpd/conf.d
        ssl_path: /etc/httpd/ssl
        log_dir: /var/log/httpd
      when: ansible_os_family == 'RedHat'
    - name: Install {{ package_name }}
      package:
        name: "{{ package_name }}"
        state: present
    - name: Make directories
      file:
        path: "{{ item }}"
        state: directory
        recurse: yes
      loop:
        - "{{ ssl_path }}/certs"
        - "{{ ssl_path }}/private"
        - /var/www/galaxy
    - name: Upload the lappsgrid key and certificate
      copy:
        src: "{{ certificate_path }}/{{ item.file }}"
        dest: "{{ ssl_path }}/{{ item.dir }}/{{ item.file }}"
      loop:
        - file: lappsgrid.key
          dir: private
        - file: lappsgrid.crt
          dir: certs
        - file: lappsgrid-root.crt
          dir: certs
    - name: Make sure permissions are correct for the key and certificates
      file:
        path: "{{ item.file }}"
        mode: "{{ item.mode }}"
        recurse: yes
      loop:
        - file: "{{ ssl_path }}/certs"
          mode: '644'
        - file: "{{ ssl_path }}/private"
          mode: '600'
    - name: Enable required apache modules
      apache2_module:
        name: "{{ item }}"
        state: present
      loop: "{{ required_modules }}"
    - name: Install mod_ssl (Debian|Ubuntu)
      apache2_module:
        name: ssl
        state: present
      when: os_debian
    - name: Install mod_ssl (RedHat|CentOS)
      package:
        name: mod_ssl
        state: present
      when: os_redhat
    - name: Configure the virtual host
      vars:
        key: "{{ ssl_path }}/private/lappsgrid.key"
        certificate: "{{ ssl_path }}/certs/lappsgrid.crt"
        root_certificate: "{{ ssl_path }}/certs/lappsgrid-root.crt"
      template:
        src: templates/virtualhost.conf.j2
        dest: "{{ config_path }}/galaxy.conf"
    - name: Enable the galaxy virtual host
      command: a2ensite galaxy
      args:
        creates: /etc/apache2/sites-enabled/galaxy
      when: os_debian
    - name: Restart apache and ensure it is enabled on reboot
      service:
        name: "{{ package_name }}"
        state: restarted
        enabled: yes
