---
- hosts: galaxy
  become: yes
  vars_files:
    - vars/galaxy.yml
    - private/galaxy.yml
  vars:
    required_modules:
      - headers
      - rewrite
      - proxy
      - proxy_http
  tasks:
    - name: System configuration
      include_tasks: tasks/initialize.yml
      when: initialized is undefined or not initialized
    - name: Install {{ apache }}
      package:
        name: "{{ apache }}"
        state: present
    - name: Make directories
      file:
        path: "{{ item }}"
        state: directory
        recurse: yes
      loop:
        - "{{ ssl_path }}/certs"
        - "{{ ssl_path }}/private"
        - "{{ doc_root }}"
    - name: Upload the lappsgrid key and certificate
      copy:
        src: "{{ certificate_path }}/{{ item.file }}"
        dest: "{{ ssl_path }}/{{ item.dir }}/{{ item.file }}"
      loop:
        - file: lappsgrid.key
          dir: private
        - file: lappsgrid.crt
          dir: certs
        - file: lappsgrid-root.crt
          dir: certs
    - name: Make sure permissions are correct for the key and certificates
      file:
        path: "{{ item.file }}"
        mode: "{{ item.mode }}"
        recurse: yes
      loop:
        - file: "{{ ssl_path }}/certs"
          mode: '644'
        - file: "{{ ssl_path }}/private"
          mode: '600'
    - name: Enable required apache modules
      apache2_module:
        name: "{{ item }}"
        state: present
      loop: "{{ required_modules }}"
    - name: Enable SSL (Debian|Ubuntu)
      apache2_module:
        name: ssl
        state: present
      when: os_debian
    - name: Enable SSL (RedHat|CentOS)
      package:
        name: mod_ssl
        state: present
      when: os_redhat
#    - name: Enable Shibboleth
#      apache2_module:
#        name: shib
#        state: present
#      when: auth == 'shibboleth'
    - name: Configure HTTPS
      template:
        src: templates/virtualhost-443.conf.j2
        dest: "{{ config_path }}/galaxy.conf"
    - name: Configure HTTP
      template:
        src: templates/virtualhost-80.conf.j2
        dest: "{{ config_path }}/000-default.conf"
    - name: Enable both sites (Debian|Ubunut only)
      command: a2ensite {{ item }}
      loop: [ galaxy, "000-default" ]
      args:
        creates: /etc/apache2/sites-enabled/galaxy
      when: ansible_os_family == 'Debian'
    - name: Passlib is not installed on Ubuntu
      pip:
        name: passlib
        state: present
    - name: Set a secret password during testing
      htpasswd:
        path: "{{ password_file }}"
        name: suderman@cs.vassar.edu
        password: password
    - name: Restart apache and ensure it is enabled on reboot
      service:
        name: "{{ apache }}"
        state: restarted
        enabled: yes
