---
- hosts: galaxy
  become: yes
  vars:
    # The location of the LAPPS Grid certificates and private key.  These must be loaded from a secure
    # location on your local machine.
    # DO NOT CHECK THE PRIVATE KEY INTO SOURCE CONTROL!
    certificate_path: /Users/suderman/certs/2018
    ssl_path: /etc/apache/ssl
    required_packages:
      - apache2
      - emacs
    required_modules:
      - ssl
      - rewrite
      - proxy
      - http_proxy
      - xsendfile
  tasks:
    - name: Install required package {{ item }}
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop: "{{ required_packages }}"
    - name: Make directories
      file:
        path: "{{ ssl_path }}/{{ item }}"
        state: directory
        recurse: yes
      loop: [ 'certs', 'private' ]
    - name: Upload the lappsgrid key and certificate
      copy:
        src: "{{ certificate_path }}/{{ item.file }}"
        dest: "{{ ssl_path }}/{{ item.dir }}/{{ item.file }}"
      loop:
        - file: lappsgrid.key
          dir: private
        - file: lappsgrid.crt
          dir: certs
        - file: lappsgrid-root.crt
          dir: certs
    - name: Make sure permissions are correct for the key and certificates
      file:
        path: "{{ item.file }}"
        mode: "{{ item.mode }}"
        recurse: yes
      loop:
        - file: "{{ ssl_path }}/certs"
          mode: '644'
        - file: "{{ ssl_path }}/private"
          mode: '600'
    - name: Configure the virtual host
      vars:
        key: "{{ ssl_path }}/private/lappsgrid.key"
        certificate: "{{ ssl_path }}/certs/lappsgrid.crt"
        root_certificate: "{{ ssl_path }}/certs/lappsgrid-root.crt"
      template:
        src: templates/virtualhost.conf.j2
        dest: /etc/apache2/sites-available/galaxy.conf
    - name: Enable required apache modules
      apache2_module:
        name: "{{ item }}"
        state: present
      loop: "{{ required_modules }}"
