---
- hosts: ubuntu
  vars_files:
    - vars/defaults.yml
    - private/galaxy.yml
  tasks:
    - name: Create the galaxy user account
      user:
        name: galaxy
        system: yes
        createhome: yes
        state: present
        shell: /bin/bash
- hosts: ub1
  vars_files:
    - vars/defaults.yml
    - private/galaxy.yml
  tasks:
    - name: Clone the Galaxy repository
      git:
        repo: "{{ item.repo }}"
        dest: "{{ item.home }}"
        version: "{{ item.branch }}"
      loop:
        - "{{ galaxy }}"
        - "{{ mods }}"
    - name: Configure the galaxy.yml file
      template:
        src: templates/galaxy.ini.j2
        dest: "{{ galaxy.home }}/config/galaxy.ini"
    - name: Install gxformat2
      pip:
        name: gxformat2
        state: present
        virtualenv: "{{ galaxy.home }}/.venv"
    - name: Make sure the Galaxy user owns its directories
      file:
        path: "{{ item }}"
        owner: "{{ galaxy.user }}"
        group: "{{ galaxy.user }}"
        recurse: yes
      loop:
        - "{{ galaxy.home }}"
        - "{{ mods.home }}"
- hosts: ub2
  vars_files:
    - vars/defaults.yml
    - private/galaxy.yml
  tasks:
    - name: Clone the Galaxy repository
      git:
        repo: "{{ item.repo }}"
        dest: "{{ item.home }}"
        version: "{{ item.branch }}"
      loop:
        - "{{ project }}"
    - name: Copy the galaxy.yml file
      copy:
        src: "files/galaxy-config.yml"
        dest: "{{ galaxy.home }}/config/galaxy.yml"
    - name: Make sure the Galaxy user owns its directories
      file:
        path: "{{ item }}"
        owner: "{{ galaxy.user }}"
        group: "{{ galaxy.user }}"
        recurse: yes
      loop:
        - "{{ project.home }}"
