
- hosts: localhost
  vars:
    flavor: m1.small
  vars_files:
    - vars/jetstream.yml
  tasks:
    - name: Create Jetstream instance
      os_server:
        state: present
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        flavor: "{{ flavor }}"
        key_name: lappsgrid-shared-key
        security_groups: galaxy
        floating_ips:
          - "{{ item.ip }}"
        nics:
          - net-id: "{{ network }}"
      loop:
        - "{{ ubuntu }}"
        - "{{ centos }}"

