---
# Destroy Jetstream instances created by the jetstream.yml playbook.
# To use this playbook you MUST source the openrc.sh file with your OpenStack API credentials for IU.
- hosts: localhost
  vars_files:
    vars/jetstream.yml
  tasks:
    - name: Delete Jetstream instance(s)
      os_server:
        state: absent
        name: "{{ item.name }}"
        image: "{{ item.image }}"
      loop: "{{ servers }}"

