---
- hosts: galaxy
  vars:
    http_port: 80
    domain: sso.lappsgrid.org
    hostname: "{{ domain }}"
    entity_id: https://{{ domain }}/shibboleth
    #sso_entity_id: https://shibboleth.brandeis.edu/idp/shibboleth
    sso_entity_id: https://samltest.id/saml/idp
  become: yes
  tasks:
    - name: Install Shibboleth (Debian|Ubuntu)
      block:
        - name: Install repository
          apt:
            state: present
            deb: https://pkg.switch.ch/switchaai/ubuntu/dists/bionic/main/binary-all/misc/switchaai-apt-source_1.0.0ubuntu1_all.deb
        - name: Install Shibboleth
          apt:
            name: shibboleth
            state: present
            install_recommends: yes
            autoremove: yes
            update_cache: yes
        - name: Set service name
          set_fact:
            apache: apache2
      when: ansible_os_family == 'Debian'
    - name: Install Shibboleth (RedHat|CentOS)
      block:
        - name: Install repository
          copy:
            src: files/shibboleth.repo
            dest: /etc/yum.repos.d/shibboleth.repo
        - name: Install Shibboleth
          yum:
            name: shibboleth.x86_64
            state: present
            update_cache: yes
        - name: Set service name
          set_fact:
            apache: httpd
      when: ansible_os_family == 'RedHat'
    - name: Copy our shibboleth2.xml
      template:
        src: templates/shibboleth2.xml.j2
        dest: /etc/shibboleth/shibboleth2.xml
    - name: Get the incommon signing key
      get_url:
        url: http://md.incommon.org/certs/inc-md-cert-mdq.pem
        dest: /etc/shibboleth
    - name: Generate keys and certificates (Debian|Ubuntu)
      command: shib-keygen -f -u _shibd -h {{ hostname }} -e {{ entity_id }} -o /etc/shibboleth -n sp-{{ item }}
      loop: [ encrypt, signing ]
      when: ansible_os_family == 'Debian'
    - name: make sure shibd owns its directory
      file:
        path: /etc/shibboleth
        owner: _shibd
        group: _shibd
        recurse: yes
    - name: Enable shibd service
      service:
        name: shibd
        state: restarted
        enabled: yes
