---
- hosts: galaxy
  tasks:
    - name: System configuration.
      include_tasks: tasks/init.yml
    - debug:
        var: "{{ item }}"
      loop:
        - ssl_path
        - config_path
        - apache
        - server_name
