---
- hosts: localhost
  vars:
    galaxy_branch: lapps
    mods_branch: master
  vars_files:
    - vars/defaults.yml
  tasks:
#    - include_tasks: tasks/parse-command-line.yml
    - name: Print galaxy
      debug:
        var: galaxy
    - debug:
        var: mods