---
- hosts: localhost
  vars:
    galaxy_branch: lapps
    mods_branch: master
  vars_files:
    - vars/defaults.yml
  tasks:
#    - include_tasks: tasks/parse-command-line.yml
    - name: Facts
      set_fact:
        "{{item.fact}}" : "{{item.value}}"
      loop:
        - fact: enabled
          value: yes
        - fact: greeting
          value: Hello world
    - debug:
        var: enabled
    - debug:
        var: greeting
      when: "{{enabled}}"
