---
- name: Installing required packages.
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ required_packages }}"
- name: Installing Java
  apt:
    name: openjdk-8-jdk
    state: present
