---
# This playbook creates a new instance on Jetstream/TACC.
#
# You MUST source your openrc.sh for TACC before any of the OpenStack
# commands will work. 
# 
# VARS
#
# os_name: the name of the instance that will be started. Required.
# os_size: the flavor size. Must be one of tiny, small, quad, medium, or large.
#          Defaults to medium.
#
# EXAMPLES
#
# $> ansible-playbook os-server.yml -e 'os_name=my-server'
# $> ansible-playbook os-server.yml -e 'os_name=my-tiny-server os_size=tiny'

- hosts: localhost
  tasks:
  - name: Setup
    include_vars: variables.yml
  - name: Check
    fail:
      msg: "os_name has not been defined."
    when: os_name is undefined
  - name: Launch a {{ os_size }} instance
    os_server:
      state: present
      name: "{{ os_name }}"
      image: "{{ ubuntu_18_04 }}"
      flavor: m1.{{ os_size | default('medium') }}
      key_name: tacc-shared-key
      security_groups: "{{ os_sec_group | default('solr') }}"
      auto_ip: no
      nics:
      - net-id: "{{ lapps_network }}"
