---
- hosts: solr
  vars:
    version: 8.4.1
  become: yes
  become_user: root
  tasks:
  - name: Check if the service exists.
    stat:
      path: /etc/init.d/solr
    register: solr_service
  - name: Stop the service
    systemd:
      name: solr
      state: stopped
      enabled: no
    when: solr_service.stat.exists == true
  - name: Unmount the volume
    mount:
      path: /var/data
      state: absent
  - name: Delete the solr user
    user:
      name: solr
      state: absent
  - name: Delete files and directories
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /tmp/solr-{{ version }}.tgz
      - /home/solr
      - /home/solr-{{ version }}
      - /opt/solr
      - /opt/solr-{{ version }}
      - /var/data/solr
      - /var/solr
      - /tmp/*.sh
      - /tmp/*.gz
      - /etc/init.d/solr
      - /etc/default/solr.in.sh
      - /etc/systemd/system/solr.service