---
- hosts: solr
  become: yes
  vars:
    user_name: solr
    dest: /opt/solr
    init_d: /etc/init.d/solr
  tasks:
  - name: Check the init.d file
    stat:
      path: "{{ init_d }}"
    register: solr_init
  - name: Disable current service
    service:
      name: solr
      state: stopped
      enabled: no
    when: solr_init.stat.exists == true    
  - name: Remove sysv init.d files
    file:
      path: /etc/init.d/solr
      state: absent
  - name: Generate solr.service from template
    template:
      src: templates/solr.service.j2
      dest: /etc/systemd/system/solr.service
      owner: solr
      mode: 0755
  - name: Enable the solr service
    systemd:
      name: solr
      enabled: yes
      masked: no
      daemon_reload: yes
      state: restarted
  - name: make sure daemon is restarted (anisble bug?)
    shell: systemctl daemon-reload
  - name: Restart solr
    service:
      name: solr
      state: restarted
      enabled: yes